const movies = [
  {
    num: 6547,
    name: "La Duquesa (2020)",
    stream_type: "movie",
    stream_id: 959321,
    tmdb_id: 572299,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/svEKCyQmJs3ZRu4YC6rQl248AAs.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1680226953",
    is_adult: "0",
    category_id: "129",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6548,
    name: "La Doble Vida 2013",
    stream_type: "movie",
    stream_id: 987300,
    tmdb_id: 174341,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/uPT0xz7XYLruX2WQRpOCBfgprOB.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1690990322",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6549,
    name: "La Disputa (2021)",
    stream_type: "movie",
    stream_id: 958290,
    tmdb_id: 840283,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/uTElTRh5Kiw06PK8GZ9HKBGIf1u.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680226613",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6550,
    name: "La diosa del asfalto (2020)",
    stream_type: "movie",
    stream_id: 958189,
    tmdb_id: 572637,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/iTLhreg2HTSZITZVzVTF23MFsVf.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680226578",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6551,
    name: "La Dimensión Desconocida (1983)",
    stream_type: "movie",
    stream_id: 879011,
    tmdb_id: 15301,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/s66HVGW0sxQWvh7APdzgEKF4XYP.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1678898647",
    is_adult: "0",
    category_id: "141",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6552,
    name: "La Deuda 2 (2020)",
    stream_type: "movie",
    stream_id: 959522,
    tmdb_id: 647785,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/tGgCTPrWqyyUpfXVXETBmmOQdHr.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680227020",
    is_adult: "0",
    category_id: "153",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6553,
    name: "La Deuda (2018)",
    stream_type: "movie",
    stream_id: 958277,
    tmdb_id: 513691,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/lPsEhmLVqzwbMNf1jjfEAia0viC.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1680226608",
    is_adult: "0",
    category_id: "153",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6554,
    name: "La designada ultra fea",
    stream_type: "movie",
    stream_id: 417239,
    tmdb_id: 272693,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/nDfF22C1ZxX0QX7lW16YYstru8l.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1664207887",
    is_adult: "0",
    category_id: "129",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6555,
    name: "La desconocida (2023)",
    stream_type: "movie",
    stream_id: 1000413,
    tmdb_id: 886544,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/t2EEPT4UBwppzi5LbjvkUemIJII.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1697988244",
    is_adult: "0",
    category_id: "211",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6556,
    name: "La desaparición de mamá (2021)",
    stream_type: "movie",
    stream_id: 959854,
    tmdb_id: 831223,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/mzTNGnLG6LTHmrqrY0IADHDuyOJ.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1680227132",
    is_adult: "0",
    category_id: "148",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6557,
    name: "La delgada línea amarilla (2015)",
    stream_type: "movie",
    stream_id: 999392,
    tmdb_id: 268854,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/uRkBY6BJzw0n36ddTpX8uXFD8RS.jpg",
    rating: "8",
    rating_5based: 4,
    added: "1697204643",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6558,
    name: "La decisión más difícil (2009)",
    stream_type: "movie",
    stream_id: 952204,
    tmdb_id: 10024,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/bvLsfZfaqGiq46lEbtWj7WuQjZ9.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1680178337",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6559,
    name: "La decisión de partir (2022)",
    stream_type: "movie",
    stream_id: 793830,
    tmdb_id: 705996,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/z9Tk2tkXL2zmbAuYr8staL0SZWO.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1677827284",
    is_adult: "0",
    category_id: "125",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6560,
    name: "La danza de la Pantera Borracha",
    stream_type: "movie",
    stream_id: 418115,
    tmdb_id: 49642,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/7t5RfG2XkqOJou60mS7mRgDJssI.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1664235737",
    is_adult: "0",
    category_id: "183",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6561,
    name: "La Dama y el Vagabundo II: Las aventuras de Scamp",
    stream_type: "movie",
    stream_id: 952408,
    tmdb_id: 18269,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/o5t3cPvAQAb1gxP6ySqNdDJ0289.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680178405",
    is_adult: "0",
    category_id: "102",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6562,
    name: "La dama y el vagabundo (1955)",
    stream_type: "movie",
    stream_id: 1037948,
    tmdb_id: 10340,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/j4in9pWwnYeXyf1Z3303nXbzFAS.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1717018566",
    is_adult: "0",
    category_id: "102",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6563,
    name: "La dama del silencio El caso de la Mataviejitas (2023)",
    stream_type: "movie",
    stream_id: 986342,
    tmdb_id: 1142216,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/wB6ez9v9HzSLplIy6m00SPIkuH7.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1690590483",
    is_adult: "0",
    category_id: "124",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6564,
    name: "La dama de Shanghai (1947)",
    stream_type: "movie",
    stream_id: 1001298,
    tmdb_id: 3766,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/uW5BCzJuYVgoSvQOC0bIYevUpXX.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1698852002",
    is_adult: "0",
    category_id: "118",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6565,
    name: "La dama de oro (2015)",
    stream_type: "movie",
    stream_id: 952255,
    tmdb_id: 304357,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/qkqlBlpeSv65GPKtWT0C7tXN2XJ.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1680178353",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6566,
    name: "La Dama de Negro 2: El ángel de la muerte (2014)",
    stream_type: "movie",
    stream_id: 953507,
    tmdb_id: 288158,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/pjbHHk0R66Xe3R6fPfuUdiGDcqH.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1680178762",
    is_adult: "0",
    category_id: "148",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6567,
    name: "La Dama de Negro (2012)",
    stream_type: "movie",
    stream_id: 952972,
    tmdb_id: 65086,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/A4Tvw1VHI6zAETyPvkiriNCJkAp.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680178587",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6568,
    name: "La célula (2000)",
    stream_type: "movie",
    stream_id: 959920,
    tmdb_id: 8843,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/vBJuude7Wgb2h9VJvid7ExZigsU.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680227160",
    is_adult: "0",
    category_id: "141",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6569,
    name: "La Cápsula del Tiempo (2018)",
    stream_type: "movie",
    stream_id: 957792,
    tmdb_id: 517055,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/ySxtdwzbH2FPJ4YPN9bmHcQy7fX.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1680226444",
    is_adult: "0",
    category_id: "116",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6570,
    name: "La cura siniestra (2017)",
    stream_type: "movie",
    stream_id: 981498,
    tmdb_id: 340837,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/k4XZ47wFZF1aUv7bjLM4Pae2TYm.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1689038402",
    is_adult: "0",
    category_id: "141",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6571,
    name: "La cumbre de los dioses (2021)",
    stream_type: "movie",
    stream_id: 957446,
    tmdb_id: 712454,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/xHJAunNc8wyC4hOprU1Vur7dgSs.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1680226331",
    is_adult: "0",
    category_id: "102",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6572,
    name: "La cueva",
    stream_type: "movie",
    stream_id: 729521,
    tmdb_id: 253376,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/4OQx9GlkPKFpNSEp4vedPmyC3vU.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1676681548",
    is_adult: "0",
    category_id: "141",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6573,
    name: "La Cuadrilla Cat, un evento exclusivo de Paw Patrol (2022)",
    stream_type: "movie",
    stream_id: 1010961,
    tmdb_id: 991833,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/l3rIbP71sR7hKtz77E6x7mdz6vG.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1705555202",
    is_adult: "0",
    category_id: "102",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6574,
    name: "La Cuadrilla Cat, un evento exclusivo de Paw Patrol",
    stream_type: "movie",
    stream_id: 417089,
    tmdb_id: 991833,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/l3rIbP71sR7hKtz77E6x7mdz6vG.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1664207746",
    is_adult: "0",
    category_id: "102",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6575,
    name: "La cruz de hierro (1977)",
    stream_type: "movie",
    stream_id: 983167,
    tmdb_id: 10839,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/kgCYqxolMwhZ4zTe1LNig1ql796.jpg",
    rating: "7",
    rating_5based: 3.5,
    added: "1689729124",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6576,
    name: "La cruda verdad (2009)",
    stream_type: "movie",
    stream_id: 952585,
    tmdb_id: 20943,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/vSQuBXiIdIvaeKDFPFvLXKNVFT8.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680178457",
    is_adult: "0",
    category_id: "129",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6577,
    name: "La criatura perfecta (2005)",
    stream_type: "movie",
    stream_id: 958347,
    tmdb_id: 18726,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/zos485avsO56zidMnReuWz3OqD9.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1680226630",
    is_adult: "0",
    category_id: "153",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6578,
    name: "La criatura (2004)",
    stream_type: "movie",
    stream_id: 952958,
    tmdb_id: 8555,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/19lWSQXvUM9KrQrPrPOeYUqBNj.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1680178592",
    is_adult: "0",
    category_id: "141",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6579,
    name: "La creciente (2019)",
    stream_type: "movie",
    stream_id: 957974,
    tmdb_id: 628194,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/wXTLAUweojIcUQ5YUCIbPXfwspt.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1680226504",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6580,
    name: "La cosa del otro mundo (2011)",
    stream_type: "movie",
    stream_id: 958036,
    tmdb_id: 60935,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/p3ysBtfK6bPVLXRwsPzVdRlmkdI.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680226525",
    is_adult: "0",
    category_id: "141",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6581,
    name: "La cosa del otro mundo (1982)",
    stream_type: "movie",
    stream_id: 958932,
    tmdb_id: 1091,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/5hkM27bPdkgQli5g5zR5pp9bkNZ.jpg",
    rating: "8",
    rating_5based: 4,
    added: "1680226824",
    is_adult: "0",
    category_id: "141",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6582,
    name: "La corriente (2023)",
    stream_type: "movie",
    stream_id: 998098,
    tmdb_id: 1076156,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/rr7lUIQ6tysyvJx14d4pG0GNrWT.jpg",
    rating: "0",
    rating_5based: 0,
    added: "1696650243",
    is_adult: "0",
    category_id: "211",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6583,
    name: "La Corresponsal (2018)",
    stream_type: "movie",
    stream_id: 952852,
    tmdb_id: 475132,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/mu2CPpT2XUVgsDEdtcelXhq5DwH.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680178546",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6584,
    name: "La Corresponsal",
    stream_type: "movie",
    stream_id: 417166,
    tmdb_id: 475132,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/mu2CPpT2XUVgsDEdtcelXhq5DwH.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1664207819",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6585,
    name: "La cordillera (2017)",
    stream_type: "movie",
    stream_id: 959778,
    tmdb_id: 440374,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/bjrdb6VLEtBcdcKGbyhRfNe51eo.jpg",
    rating: "5",
    rating_5based: 2.5,
    added: "1680227110",
    is_adult: "0",
    category_id: "123",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6586,
    name: "La corazonada (2020)",
    stream_type: "movie",
    stream_id: 953266,
    tmdb_id: 620883,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/8UxtCBZiZ72GjNIoGAVKPrOD36T.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1680178684",
    is_adult: "0",
    category_id: "148",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6587,
    name: "La conspiración del poder",
    stream_type: "movie",
    stream_id: 652322,
    tmdb_id: 16325,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/pmRseLtbNMr7WVjR82W10PsUY0r.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1669044443",
    is_adult: "0",
    category_id: "153",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
  {
    num: 6588,
    name: "La Conspiración del Diablo (2023)",
    stream_type: "movie",
    stream_id: 1004604,
    tmdb_id: 296271,
    stream_icon:
      "https://image.tmdb.org/t/p/w400/p1czkLtquPkiQg3OqubHqNzr6jM.jpg",
    rating: "6",
    rating_5based: 3,
    added: "1701749282",
    is_adult: "0",
    category_id: "141",
    container_extension: "mp4",
    custom_sid: "",
    direct_source: "",
  },
];

const moviesCategories2 = [
  {
    category_id: "233",
    category_name: "Estrenos 2025",
    parent_id: 0,
  },
  {
    category_id: "220",
    category_name: "Estrenos 2024",
    parent_id: 0,
  },
  {
    category_id: "185",
    category_name: "Estrenos 2023",
    parent_id: 0,
  },
  {
    category_id: "224",
    category_name: "Netflix",
    parent_id: 0,
  },
  {
    category_id: "175",
    category_name: "Calidad Cam",
    parent_id: 0,
  },
  {
    category_id: "219",
    category_name: "Felices Fiestas",
    parent_id: 0,
  },
  {
    category_id: "153",
    category_name: "Acci\u00f3n",
    parent_id: 0,
  },
  {
    category_id: "183",
    category_name: "Artes Marciales",
    parent_id: 0,
  },
  {
    category_id: "101",
    category_name: "Aventura",
    parent_id: 0,
  },
  {
    category_id: "102",
    category_name: "Animaci\u00f3n",
    parent_id: 0,
  },
  {
    category_id: "103",
    category_name: "Anime",
    parent_id: 0,
  },
  {
    category_id: "209",
    category_name: "Religi\u00f3n",
    parent_id: 0,
  },
  {
    category_id: "170",
    category_name: "B\u00e9lica",
    parent_id: 0,
  },
  {
    category_id: "211",
    category_name: "Castellano",
    parent_id: 0,
  },
  {
    category_id: "186",
    category_name: "Cristianas",
    parent_id: 0,
  },
  {
    category_id: "129",
    category_name: "Comedia",
    parent_id: 0,
  },
  {
    category_id: "125",
    category_name: "Crimen",
    parent_id: 0,
  },
  {
    category_id: "124",
    category_name: "Documental",
    parent_id: 0,
  },
  {
    category_id: "123",
    category_name: "Drama",
    parent_id: 0,
  },
  {
    category_id: "122",
    category_name: "Familia",
    parent_id: 0,
  },
  {
    category_id: "121",
    category_name: "Fantas\u00eda",
    parent_id: 0,
  },
  {
    category_id: "120",
    category_name: "Historia",
    parent_id: 0,
  },
  {
    category_id: "118",
    category_name: "Misterio",
    parent_id: 0,
  },
  {
    category_id: "119",
    category_name: "Musical",
    parent_id: 0,
  },
  {
    category_id: "116",
    category_name: "Romance",
    parent_id: 0,
  },
  {
    category_id: "117",
    category_name: "Ciencia Ficci\u00f3n",
    parent_id: 0,
  },
  {
    category_id: "140",
    category_name: "Short",
    parent_id: 0,
  },
  {
    category_id: "148",
    category_name: "Suspenso",
    parent_id: 0,
  },
  {
    category_id: "141",
    category_name: "Terror",
    parent_id: 0,
  },
  {
    category_id: "226",
    category_name: "Gaia/Yoga",
    parent_id: 0,
  },
  {
    category_id: "169",
    category_name: "Western",
    parent_id: 0,
  },
  {
    category_id: "232",
    category_name: "DramaBox",
    parent_id: 0,
  },
  {
    category_id: "184",
    category_name: "WWE",
    parent_id: 0,
  },
  {
    category_id: "174",
    category_name: "Subtitulada",
    parent_id: 0,
  },
  {
    category_id: "191",
    category_name: "18+ 4k",
    parent_id: 0,
  },
  {
    category_id: "229",
    category_name: "18+Dorcel club",
    parent_id: 0,
  },
  {
    category_id: "227",
    category_name: "18+inkasex",
    parent_id: 0,
  },
  {
    category_id: "189",
    category_name: "4K",
    parent_id: 0,
  },
];

const series = [
  {
    num: 1,
    name: "YAIBA: Samurai Legend",
    series_id: 1109163,
    tmdb_id: 254017,
    cover: "https://image.tmdb.org/t/p/w400/1jltcsz17CkfyhpcsSlmVC6pQGh.jpg",
    plot: "El viaje de Yaiba para convertirse en un verdadero samur\u00e1i lo lleva desde su hogar en la jungla hasta una ajetreada ciudad llena de rivales, amistades y poderes ancestrales.",
    cast: "\u9ad8\u5c71\u307f\u306a\u307f,Manaka Iwami",
    director: "",
    genre: "Action & Adventure / Animaci\u00f3n / Sci-Fi & Fantasy / Comedia",
    releaseDate: "2025-04-05",
    last_modified: "1764112312",
    rating: "7",
    rating_5based: 3.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/8anbNuU3e5PAvpfa8r26aZG7ubP.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "24",
    category_id: "126",
  },
  {
    num: 2,
    name: "Tokyo Revengers",
    series_id: 800500,
    tmdb_id: 105009,
    cover: "https://image.tmdb.org/t/p/w400/1cTO9iytDVPu3Tkd9VgAmukm55q.jpg",
    plot: "Takemichi es un desempleado de 26 a\u00f1os que descubre que la chica con la que sali\u00f3 en secundaria, la que fue su \u00fanica novia, ha muerto. Tras eso sufre un accidente del cual, al despertar, descubre que se ha transportado a sus a\u00f1os de secundaria. Con ello Takemichi jura que cambiar\u00e1 el futuro y salvar\u00e1 a la chica, y para hacerlo necesita llegar a ser el l\u00edder de la banda de delincuentes m\u00e1s salvaje y brutal de Kanto.",
    cast: "Yuuki Shin,Azumi Waki,Ryota Osaka,Yuu Hayashi,Tatsuhisa Suzuki,Takuma Terashima,Yuya Hirose,Shunsuke Takeuchi,Shota Hayama,Satoshi Hino,Masaaki Mizunaka,Subaru Kimura,Yukihiro Nozuyama,Kengo Kawanishi,Daisuke Ono,Eiji Takeuchi,Yoshitsugu Matsuoka,Showtaro Morikubo,Takuya Eguchi",
    director: "",
    genre: "Drama / Animaci\u00f3n / Action & Adventure / Crimen",
    releaseDate: "2021-04-11",
    last_modified: "1764112172",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/zYIFOocMfsKAEysBjhZ8akfXFdB.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "24",
    category_id: "126",
  },
  {
    num: 3,
    name: "Ninja Vs. Gokudo",
    series_id: 1105917,
    tmdb_id: 285070,
    cover: "https://image.tmdb.org/t/p/w400/a3zrH0Y5wwlIcAAGNg3aojoMwQD.jpg",
    plot: "Los ninjas eliminan el mal desde las sombras. Los gokudo se re\u00fanen como marginados y cometen cr\u00edmenes. Un viejo rencor vuelve a encenderse. El ninja Shinoha conoce a Kiwami, un gokudo que se oculta tras la fachada de un oficinista. Sin saber qui\u00e9nes son, se hacen amigos por el anime, pero la guerra entre ninjas y gokudo se intensifica. \u00bfQui\u00e9n sobrevivir\u00e1? \u00bfNinjas o gokudo?",
    cast: "",
    director: "",
    genre: "Animaci\u00f3n / Action & Adventure",
    releaseDate: "2025-10-08",
    last_modified: "1764094060",
    rating: "0",
    rating_5based: 0,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/KQDy2RJMN2gsPV5RZO1pQdFZAQ.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "126",
  },
  {
    num: 4,
    name: "Desapariciones: \u00bfVivos o muertos?",
    series_id: 968433,
    tmdb_id: 225351,
    cover: "https://image.tmdb.org/t/p/w400/pTSzU9gWSsbosFD9nblTIPG4gur.jpg",
    plot: "",
    cast: "",
    director: "",
    genre: "Crimen / Documental",
    releaseDate: "2023-05-10",
    last_modified: "1764091316",
    rating: "6",
    rating_5based: 3,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/slw3sELQwTkINBIIrSXi1acU2Eg.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "143",
  },
  {
    num: 5,
    name: "Todo vale",
    series_id: 1107676,
    tmdb_id: 258742,
    cover: "https://image.tmdb.org/t/p/w400/ryXszdo34k4B4VdC81u9ZcdF0qU.jpg",
    plot: "Un grupo de abogadas especialistas en divorcios abandona un bufete dominado por hombres para abrir su propio y exitoso despacho. Brillantes, feroces y emocionalmente complejas, lidian con separaciones de alto perfil, esc\u00e1ndalos y lealtades cambiantes, tanto en los tribunales como en su c\u00edrculo \u00edntimo. En un mundo donde el dinero manda y el amor es un campo de batalla, estas mujeres no solo juegan, sino que cambian las reglas.",
    cast: "Kim Kardashian,Naomi Watts,Niecy Nash-Betts,Teyana Taylor,Matthew Noszka,Sarah Paulson,Glenn Close",
    director: "Jon Robin Baitz,Joe Baken,Ryan Murphy",
    genre: "Drama / Comedia",
    releaseDate: "2025-11-04",
    last_modified: "1764091212",
    rating: "7",
    rating_5based: 3.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/cfRdpQXWn7JDkXTkWJSf5dIUdla.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "134",
  },
  {
    num: 6,
    name: "Encantado de no conocerte",
    series_id: 1107682,
    tmdb_id: 285770,
    cover: "https://image.tmdb.org/t/p/w400/rzBSOFKqayEEIUwZJyWcg3Fb1th.jpg",
    plot: "En esta comedia, un en\u00e9rgico actor encasillado y una obstinada periodista pol\u00edtica forman una alianza at\u00edpica contra las barreras que les imponen.",
    cast: "Lee Jung-jae,\uc784\uc9c0\uc5f0,\uae40\uc9c0\ud6c8,\uc11c\uc9c0\ud61c,\ucd5c\uadc0\ud654,Kim Hyun-jin,\ub098\uc601\ud76c,\uc9c4\ud638\uc740,\uc804\uc218\uacbd,\uae40\uc7ac\ucca0,\uae40\ubc95\ub798,\uc870\ud76c\ubd09,\uc804\uc131\uc6b0",
    director: "Kim Ga Ram",
    genre: "Comedia",
    releaseDate: "2025-11-03",
    last_modified: "1764091037",
    rating: "6",
    rating_5based: 3,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/fc4Shbli2S1BwUgoTjvP3BIM9VX.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "151",
  },
  {
    num: 7,
    name: "Dinastia Casillas",
    series_id: 1105467,
    tmdb_id: 302463,
    cover: "https://image.tmdb.org/t/p/w400/xbBJBKssJr85OzAJNSuWdkh5p4v.jpg",
    plot: "Tras la desaparici\u00f3n de Aurelio, Ismael Casillas se ve envuelto en una guerra implacable por su legado y su familia que requiere nuevas alianzas y sacrificios.",
    cast: "Iv\u00e1n Arana,Mar\u00eda Fernanda Yepes,Ra\u00fal M\u00e9ndez,Isabella Castillo",
    director: "Juan Camilo Ferrand",
    genre: "Drama / Action & Adventure / Misterio",
    releaseDate: "2025-10-07",
    last_modified: "1764085751",
    rating: "0",
    rating_5based: 0,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/evspTA2K2ACB34uIsWgvkAL5Xb7.jpg",
    ],
    youtube_trailer: "Z2H3KY3Wnr4",
    episode_run_time: "",
    category_id: "195",
  },
  {
    num: 8,
    name: "Renacer",
    series_id: 1105042,
    tmdb_id: 245914,
    cover: "https://image.tmdb.org/t/p/w400/nvRuGsibq4z2prDu10bWiszugIE.jpg",
    plot: "Bahar se gradu\u00f3 de la escuela de medicina, pero eligi\u00f3 la familia antes que la carrera. La aparentemente feliz familia Yavuzoglu est\u00e1 conmocionada por la enfermedad de Bahar y solo el h\u00edgado de su esposo Timur puede salvarla.",
    cast: "Demet Evgar,Bu\u011fra G\u00fclsoy,Ecem \u00d6zkaya,Elit Anda\u00e7 \u00c7am,Demirhan Demircio\u011flu,Nil Sude Albayrak,F\u00fcsun Demirel,Hatice Aslan,Alisa Sezen Sever,Hasan \u015eahint\u00fcrk,Sena Kal\u0131p,Devrim Kabacao\u011flu,Ege Erkal,Mert Turak,Hayal K\u00f6seo\u011flu",
    director: "Neslihan Ye\u015filyurt",
    genre: "Familia / Drama",
    releaseDate: "2024-02-13",
    last_modified: "1764021185",
    rating: "6",
    rating_5based: 3,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/6dXyUXZ4HsY6M3Tae9e0KZsFCo1.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "135",
    category_id: "187",
  },
  {
    num: 9,
    name: "Robin Hood",
    series_id: 1109052,
    tmdb_id: 272418,
    cover: "https://image.tmdb.org/t/p/w400/3teWChNzKJdbfen46IdeKTygdZa.jpg",
    plot: "Serie que reimagina la leyenda de Robin Hood, con un enfoque moderno del forajido que roba a los ricos para d\u00e1rselo a los pobres y la historia de amor entre \u00e9l y Marian. Tras la invasi\u00f3n normanda de Inglaterra, Rob, hijo de un guardabosques saj\u00f3n, y Marian, hija de un lord normando, se enamoran y luchan juntos por la justicia y la libertad. Mientras Rob se convierte en el l\u00edder de una banda de forajidos rebeldes, Marian se infiltra en el poder de la corte, y ambos trabajan juntos para frustrar la corrupci\u00f3n real y traer la paz a la tierra.",
    cast: "Jack Patten,Lauren McQueen,Lydia Peckham,Marcus Fraser,Henry Rowley,Erica Ford,Angus Castle-Doughty,Steven Waddington,Connie Nielsen,Sean Bean",
    director: "Jonathan English,John Glenn",
    genre: "Drama / Action & Adventure",
    releaseDate: "2025-11-02",
    last_modified: "1764021099",
    rating: "7",
    rating_5based: 3.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/uoIOfRNmu47P2fET2KnrYHt3TH.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "115",
  },
  {
    num: 10,
    name: "El Jefe De Kingstown",
    series_id: 970479,
    tmdb_id: 97951,
    cover: "https://image.tmdb.org/t/p/w400/s18V51BeLOr9vB0rXm3QcVS6wwL.jpg",
    plot: "Ambientada en una peque\u00f1a ciudad de Michigan, donde los \u00fanicos negocios que sobrevivieron son las prisiones federales, estatales y privadas, la historia sigue a la familia McClusky, intermediaria entre la polic\u00eda, los criminales, delincuentes, guardias de la prisi\u00f3n y pol\u00edticos, en una ciudad completamente dependiente de las prisiones y los prisioneros que se encuentran en ellas.",
    cast: "Jeremy Renner,Dianne Wiest,Hugh Dillon,Tobi Bamtefa,Taylor Handley,Emma Laird,Derek Webster,Hamish Allan-Headley,Nishi Munshi,Aidan Gillen",
    director: "Hugh Dillon,Taylor Sheridan",
    genre: "Drama / Crimen",
    releaseDate: "2021-11-14",
    last_modified: "1764021035",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/gQxaF79LUTtopdYHsuS8lUr9rvF.jpg",
    ],
    youtube_trailer: "zhmIVF2dTbI",
    episode_run_time: "",
    category_id: "134",
  },
  {
    num: 11,
    name: "Smiling Friends",
    series_id: 1105991,
    tmdb_id: 126506,
    cover: "https://image.tmdb.org/t/p/w400/l1Qdw9DsJaomE8BXeVfkF6h1qaa.jpg",
    plot: "Serie animada para adultos que cuenta las locas aventuras de los empleados de una empresa que se dedica a repartir felicidad por un mundo extra\u00f1o pero colorido.",
    cast: "Michael Cusack,Zach Hadel,Marc Moceri",
    director: "Michael Cusack,Zach Hadel",
    genre: "Animaci\u00f3n / Comedia",
    releaseDate: "2020-04-01",
    last_modified: "1764009278",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/msAljUxkBtPB9GoQgGXzf4GFR3M.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "11",
    category_id: "128",
  },
  {
    num: 12,
    name: "The Chair Company",
    series_id: 1106153,
    tmdb_id: 271267,
    cover: "https://image.tmdb.org/t/p/w400/xZgftEXZXTM47k2rZlXo8kr8HZF.jpg",
    plot: "Tim Robinson protagoniza esta serie de HBO como un hombre que, tras un incidente vergonzoso en el trabajo, termina investigando una gran conspiraci\u00f3n.",
    cast: "Tim Robinson,Lake Bell,Sophia Lillis,Will Price,Joseph Tudisco",
    director: "Tim Robinson,Zach Kanin",
    genre: "Comedia",
    releaseDate: "2025-10-12",
    last_modified: "1764009095",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/4mWtAo747prNwNqqmE4upngsbgY.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "30",
    category_id: "114",
  },
  {
    num: 13,
    name: "I Love LA",
    series_id: 1107674,
    tmdb_id: 271053,
    cover: "https://image.tmdb.org/t/p/w400/6xrLXEQABvoVwGka9KDDAOt4lFs.jpg",
    plot: "Maia, que aspira a ser representante art\u00edstica, est\u00e1 estancada como asistente mientras vive con su novio... hasta que regresa su mejor amiga de toda la vida, la fren\u00e9tica influencer Tallulah.",
    cast: "Rachel Sennott,Odessa A'zion,Jordan Firstman,True Whitaker,Josh Hutcherson,Quen Blackwell",
    director: "Rachel Sennott",
    genre: "Comedia",
    releaseDate: "2025-11-02",
    last_modified: "1764008541",
    rating: "5",
    rating_5based: 2.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/ljfI31geKnqP3K7EECp9z0ALyFB.jpg",
    ],
    youtube_trailer: "vjNVCdOHxAY",
    episode_run_time: "",
    category_id: "114",
  },
  {
    num: 14,
    name: "Al Fondo Hay Sitio",
    series_id: 887681,
    tmdb_id: 32209,
    cover: "https://image.tmdb.org/t/p/w400/g7cuCCkvoBuSwemTHYz3k0hvvmz.jpg",
    plot: "Una de las zonas residenciales m\u00e1s exclusivas de Lima se ve sacudida con la llegada de LOS GONZALES, una familia que viene de provincia a establecerse en una casa heredada a medio construir. Sus costumbres campechanas incomodar\u00e1n a los vecinos, sobre todo a LOS MALDINI que no saben c\u00f3mo deshacerse de los reci\u00e9n llegados...",
    cast: "Yvonne Frayssinet,Giovanni Ciccia,M\u00f3nica S\u00e1nchez,Gustavo Bueno,Adolfo Chuiman,Magdyel Ugaz,Erick Elera,Maria Grazia Gamarra,L\u00e1szl\u00f3 Kov\u00e1cs,David Almandoz,Jorge Guerra Wiesse,Karime Scander,Guadalupe Farf\u00e1n,Franco Pennano,Carlos Solano,Rodrigo Barba",
    director: "Efrain Aguilar",
    genre: "Comedia / Drama / Soap",
    releaseDate: "2009-03-30",
    last_modified: "1763953257",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/xYt0GHDtkeuDsPnrMT7lReWHi3T.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "42",
    category_id: "207",
  },
  {
    num: 15,
    name: "IT: Bienvenidos a Derry",
    series_id: 1107097,
    tmdb_id: 200875,
    cover: "https://image.tmdb.org/t/p/w400/vC6LSYC8uhZPkPM01L6HKrr1lMD.jpg",
    plot: "En 1958, un grupo de siete amigos est\u00e1n empezando a ver cosas extra\u00f1as en el tranquilo pueblito Derry. Con el tiempo, descubren que todos estaban viendo lo mismo: un ser sobrenatural y malvado que puede adoptar muchas formas.",
    cast: "Bill Skarsg\u00e5rd,Taylour Paige,Jovan Adepo,Stephen Rider,Amanda Christine,Clara Stack,Mikkal Karim Fidler,Jack Molloy Legault,Matilda Legault,James Remar,Miles Ekhardt,Chris Chalk",
    director: "Andy Muschietti,Barbara Muschietti,Jason Fuchs",
    genre: "Misterio / Drama",
    releaseDate: "2025-10-26",
    last_modified: "1763952249",
    rating: "6",
    rating_5based: 3,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/2746UvsbkZINd873Yd3o3TxOwCP.jpg",
    ],
    youtube_trailer: "gWcb7eugjTo",
    episode_run_time: "",
    category_id: "134",
  },
  {
    num: 16,
    name: "Ten Percent",
    series_id: 923286,
    tmdb_id: 64165,
    cover: "https://image.tmdb.org/t/p/w400/zFnsSLJGGu7Ho4JRo8MwEaqViUA.jpg",
    plot: "Despu\u00e9s de una crisis, los empleados de una exitosa agencia de talentos en Par\u00eds luchan por mantener felices a sus clientes superestrellas y el negocio a flote.",
    cast: "Camille Cottin,Thibault de Montalembert,Gr\u00e9gory Montel,Liliane Rov\u00e8re,Laure Calamy,Nicolas Maury,Fanny Sidney,St\u00e9fi Celma,Oph\u00e9lia Kolb,Assaad Bouab,Anne Marivin",
    director: "Dominique Besnehard,Fanny Herrero",
    genre: "Comedia / Drama",
    releaseDate: "2015-10-14",
    last_modified: "1763950064",
    rating: "7",
    rating_5based: 3.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/4hmHHZnanKEb1fLTkmYePvENmuI.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "52",
    category_id: "114",
  },
  {
    num: 17,
    name: "Familia Typhoon",
    series_id: 1106150,
    tmdb_id: 280946,
    cover: "https://image.tmdb.org/t/p/w400/k60BloWxlWTpVumWR4cioC8OLi1.jpg",
    plot: "En plena crisis financiera de 1997, un joven despreocupado hereda el tambaleante negocio de su padre, y su nuevo rol de jefe lo lleva a entender lo que implica ser adulto.",
    cast: "Lee Junho,\uae40\ubbfc\ud558,\uae40\uc9c0\uc601,\uae40\ubbfc\uc11d,\ubb34\uc9c4\uc131,\uae40\uc601\uc625,\uc9c4\uc120\uaddc",
    director: "Lee Na-jeong",
    genre: "Drama",
    releaseDate: "2025-10-11",
    last_modified: "1763936882",
    rating: "7",
    rating_5based: 3.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/2lXNakKtadrvteeGjnLF3gcoZNL.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "151",
  },
  {
    num: 18,
    name: "La vida so\u00f1ada del Sr. Kim",
    series_id: 1107289,
    tmdb_id: 275592,
    cover: "https://image.tmdb.org/t/p/w400/jm60rnmUc9T0ScYILIn75DENPew.jpg",
    plot: "Tras haber hecho carrera en una empresa, un hombre de mediana edad emprende un camino de autodescubrimiento en el que intenta reencontrarse con la felicidad verdadera.",
    cast: "\ub958\uc2b9\ub8e1,\uba85\uc138\ube48,\ucc28\uac15\uc724,\uc815\uc740\ucc44,\uc720\uc2b9\ubaa9,\ubc15\uc218\uc601,\uace0\ucc3d\uc11d,\uc774\uc11c\ud658,\uc815\uc21c\uc6d0,\ud558\uc11c\uc724,\uc774\uc138\ud76c",
    director: "",
    genre: "Comedia / Drama",
    releaseDate: "2025-10-25",
    last_modified: "1763936653",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/yd4qmGDn0q2MWHue5dRs3sm42sO.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "151",
  },
  {
    num: 19,
    name: "Harry Potter: Magos Pasteleros",
    series_id: 1099200,
    tmdb_id: 254514,
    cover: "https://image.tmdb.org/t/p/w400/mWiPAbHQnPFsTJIpvzpGga29IkV.jpg",
    plot: "James y Oliver Phelps son los presentadores mientras parejas de pasteleros crean obras comestibles en los sets de filmaci\u00f3n reales de Harry Potter.",
    cast: "James Phelps,Oliver Phelps,Carla Hall,Jozef Youssef",
    director: "",
    genre: "Reality",
    releaseDate: "2024-11-14",
    last_modified: "1763935977",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/9mDlwBdCu501924dXnzz2Gtc8XI.jpg",
    ],
    youtube_trailer: "N5503JBM528",
    episode_run_time: "",
    category_id: "179",
  },
  {
    num: 20,
    name: "La nobleza de las flores",
    series_id: 1103108,
    tmdb_id: 271607,
    cover: "https://image.tmdb.org/t/p/w400/khxkciCkPVG1c7R00vNZFxqgqFE.jpg",
    plot: "Cuando el intimidante Rintar\u014d conoce a la tierna Kaoruko, nace una inesperada relaci\u00f3n cercana. Solo hay un peque\u00f1o problema: las escuelas a las que van son archienemigas.",
    cast: "\u4e2d\u5c71\u7965\u5fb3,\u4e95\u4e0a\u307b\u306e\u82b1",
    director: "",
    genre: "Animaci\u00f3n / Drama / Comedia",
    releaseDate: "2025-07-06",
    last_modified: "1763935866",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/dl3pdT1NZiqRM4aDBwsD2TtO8x9.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "24",
    category_id: "126",
  },
  {
    num: 21,
    name: "Landman: Un negocio crudo",
    series_id: 1068699,
    tmdb_id: 157741,
    cover: "https://image.tmdb.org/t/p/w400/hGbYOuUVoxfXa96pmNLFJ9a7U5T.jpg",
    plot: "En Texas, matones y multimillonarios intentan hacerse ricos en el negocio del petr\u00f3leo a medida que las plataformas petrol\u00edferas dominan el estado. El ejecutivo Tommy Norris intenta llevar a su empresa a lo m\u00e1s alto durante el auge del petr\u00f3leo.",
    cast: "Billy Bob Thornton,Ali Larter,Jacob Lofland,Michelle Randolph,Paulina Ch\u00e1vez,Kayla Wallace,Mark Collie,James Jordan,Demi Moore,Jon Hamm",
    director: "Taylor Sheridan,Christian Wallace",
    genre: "Drama",
    releaseDate: "2024-11-17",
    last_modified: "1763935729",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/mh2UczqEXJJVgqohbyZbHTuxwhL.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "134",
  },
  {
    num: 22,
    name: "Tulsa King",
    series_id: 736717,
    tmdb_id: 153312,
    cover: "https://image.tmdb.org/t/p/w400/yzRnj5GMZEjiW9xTGkz8cVNyzH9.jpg",
    plot: 'Justo despu\u00e9s de ser liberado de prisi\u00f3n despu\u00e9s de 25 a\u00f1os, el capo de la mafia de Nueva York, Dwight "El General" Manfredi, es exiliado sin contemplaciones por su jefe para instalarse en Tulsa, Oklahoma. Al darse cuenta de que su familia de la mafia puede no tener sus mejores intereses en mente, Dwight construye lentamente una "tripulaci\u00f3n" a partir de un grupo de personajes inveros\u00edmiles, para ayudarlo a establecer un nuevo imperio criminal en un lugar que para \u00e9l bien podr\u00eda ser otro planeta.',
    cast: "Sylvester Stallone,Andrea Savage,Max Casella,Martin Starr,Domenick Lombardozzi,Vincent Piazza,Jay Will,Alan C. Peterson,Garrett Hedlund,Dana Delany",
    director: "Taylor Sheridan",
    genre: "Crimen / Drama",
    releaseDate: "2022-11-13",
    last_modified: "1763935625",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/mNHRGO1gFpR2CYZdANe72kcKq7G.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "40",
    category_id: "134",
  },
  {
    num: 23,
    name: "Todo el dinero",
    series_id: 1106339,
    tmdb_id: 197449,
    cover: "https://image.tmdb.org/t/p/w400/p76vRTPXF5ioTv5lTlnGhOCA9fu.jpg",
    plot: "Despu\u00e9s de divorciarse de su esposo desde hace veinte a\u00f1os, Molly Novak debe averiguar qu\u00e9 hacer con sus 87 mil millones de d\u00f3lares. Decide trabajar en su fundaci\u00f3n de caridad y reconectar con el mundo real mientras se conoce a s\u00ed misma.",
    cast: "Maya Rudolph,Michaela Ja\u00e9 Rodriguez,Joel Kim Booster,Nat Faxon,Ron Funches,Stephanie Styles,Meagen Fay",
    director: "Matt Hubbard,Alan Yang",
    genre: "Comedia",
    releaseDate: "2022-06-23",
    last_modified: "1763835833",
    rating: "6",
    rating_5based: 3,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/wk1ylquzPsZFRSuGXyAfZ0gyHmV.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "",
    category_id: "114",
  },
  {
    num: 24,
    name: "Ranma1/2 (2024)",
    series_id: 1064619,
    tmdb_id: 259140,
    cover: "https://image.tmdb.org/t/p/w400/4RMFcyl0Jwib1XQlaZEQlHNUcGR.jpg",
    plot: "Akane Tendo conoce a su prometido, Ranma Saotome, un experto en artes marciales con un detallecito menor: por arte de magia, se transforma en chica cuando toca el agua fr\u00eda.",
    cast: "\u5c71\u53e3\u52dd\u5e73,\u6797\u539f\u3081\u3050\u307f,\u65e5\u9ad9\u306e\u308a\u5b50,\u9ad8\u5c71\u307f\u306a\u307f,\u4e95\u4e0a\u559c\u4e45\u5b50,\u5927\u585a\u660e\u592b,\u30c1\u30e7\u30fc",
    director: "",
    genre: "Animaci\u00f3n / Action & Adventure / Comedia / Sci-Fi & Fantasy",
    releaseDate: "2024-10-06",
    last_modified: "1763835603",
    rating: "9",
    rating_5based: 4.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/xMgzRUA1RjxLQn05oJ8IFbf06AO.jpg",
    ],
    youtube_trailer: "cfgPnq4sssU",
    episode_run_time: "23",
    category_id: "126",
  },
  {
    num: 25,
    name: "La Misi\u00f3n de la Familia Yozakura",
    series_id: 1109016,
    tmdb_id: 216467,
    cover: "https://image.tmdb.org/t/p/w400/rDTpsV3pCoqp35YJ90ZHzMr73nH.jpg",
    plot: "La serie se centra en Taiy\u014d Asano, un joven que perdi\u00f3 a toda su familia en un accidente de auto. Su amiga de la infancia, Mutsumi Yozakura, es la \u00fanica persona que le da alg\u00fan tipo de confort en la vida. Sin embargo, las cosas vuelven a cambiar en la vida de Taiy\u014d, cuando descubre que su maestro es el hermano mayor de Mutsumi, y que ella proviene de una familia de esp\u00edas.\n\nDespu\u00e9s de una pelea que envolvi\u00f3 a toda la Familia Yozakura, Taiy\u014d se termina convirtiendo en el esposo de Mutsumi el cual para ser capaz de protegerla de todas las amenazas que la atormentan, Taiy\u014d deber\u00e1 de convertirse en un esp\u00eda.",
    cast: "\u5ddd\u5cf6\u96f6\u58eb,\u672c\u6e21\u6953,\u5c0f\u897f\u514b\u5e78,\u9b3c\u982d\u660e\u91cc,\u60a0\u6728\u78a7,\u8208\u6d25\u548c\u5e78,\u677e\u5ca1\u798e\u4e1e,\u5185\u5c71\u5915\u5b9f,\u4e95\u4e0a\u548c\u5f66,\u4f0a\u702c\u8309\u8389\u4e5f,Romi Park,\u5185\u5c71\u6602\u8f1d,\u6ff1\u91ce\u5927\u8f1d,\u52a0\u702c\u5eb7\u4e4b,\u5c71\u7530\u6804\u5b50,\u3046\u3048\u3060\u3086\u3046\u3058",
    director: "",
    genre: "Animaci\u00f3n / Comedia / Action & Adventure",
    releaseDate: "2024-04-07",
    last_modified: "1763833465",
    rating: "7",
    rating_5based: 3.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/xUC6mdVESvJN2umz8mNxKn89Htf.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "25",
    category_id: "126",
  },
  {
    num: 26,
    name: "Gary y sus Demonios",
    series_id: 1108999,
    tmdb_id: 79478,
    cover: "https://image.tmdb.org/t/p/w400/wN6EU9KJ2K8fwFASuwDPWrAXkTn.jpg",
    plot: "Un cazador de demonios lucha por mantener el inter\u00e9s por algo que nunca pidi\u00f3: salvar la Tierra.",
    cast: "Tim Gilbert,Miguel Rivas,Marito Lopez,Emma Hunter,Kyle Dooley,Kayla Lorette,Laura Cilevitz,Mark Little",
    director: "Mark Little,Mark Satterthwaite",
    genre: "Animaci\u00f3n / Comedia",
    releaseDate: "2018-04-15",
    last_modified: "1763833368",
    rating: "7",
    rating_5based: 3.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/1RdheGaykWq2q8W95vkb8dK24mG.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "11",
    category_id: "128",
  },
  {
    num: 27,
    name: "Alaska: La \u00faltima frontera",
    series_id: 1105963,
    tmdb_id: 221079,
    cover: "https://image.tmdb.org/t/p/w400/rliJwdIyth2L7uWpoPDaTz1Suz0.jpg",
    plot: "Cuando un avi\u00f3n que transporta prisioneros se estrella en la remota tundra de Alaska y docenas de presidiarios violentos quedan en libertad, el \u00fanico polic\u00eda de la regi\u00f3n debe proteger al pueblo que jur\u00f3 mantener a salvo.",
    cast: "Jason Clarke,Dominic Cooper,Haley Bennett,Simone Kessell,Dallas Goldtooth,Tait Blum,Alfre Woodard",
    director: "Jon Bokenkamp,Richard D'Ovidio",
    genre: "Drama",
    releaseDate: "2025-10-09",
    last_modified: "1763833251",
    rating: "7",
    rating_5based: 3.5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/tppoXtkKVh26oEsMdkIGmUqdgVL.jpg",
    ],
    youtube_trailer: "6j5Ccr7Kd-s",
    episode_run_time: "",
    category_id: "134",
  },
  {
    num: 28,
    name: "Down Cemetery Road: El misterio de Oxford",
    series_id: 1107533,
    tmdb_id: 252000,
    cover: "https://image.tmdb.org/t/p/w400/95wXEqlXUWrKtf54EUpb5JJpis3.jpg",
    plot: "Cuando una ni\u00f1a desaparece despu\u00e9s de la explosi\u00f3n de una casa, una vecina preocupada se une a un investigador privado para encontrarla. Una conspiraci\u00f3n militar emerge y mientras se revelan secretos, se desata el caos en el sur de Oxford.",
    cast: "Emma Thompson,Ruth Wilson,Adeel Akhtar,Nathan Stewart-Jarrett,Tom Goodman-Hill,Darren Boyd,Tom Riley,Adam Godley,Sinead Matthews,Ken Nwosu,Fehinti Balogun,Aiysha Hart",
    director: "",
    genre: "Drama / Crimen / Misterio",
    releaseDate: "2025-10-29",
    last_modified: "1763776343",
    rating: "10",
    rating_5based: 5,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/44C0YSeSu7MJaBVmNZtHiQsadj3.jpg",
    ],
    youtube_trailer: "g4jm7E8MKGA",
    episode_run_time: "",
    category_id: "134",
  },
  {
    num: 29,
    name: "Pluribus",
    series_id: 1107901,
    tmdb_id: 225171,
    cover: "https://image.tmdb.org/t/p/w400/5OLUjOrgXzXrPl2PEgZGHgpQSO9.jpg",
    plot: "La persona m\u00e1s infeliz del planeta debe salvar al mundo de la felicidad.",
    cast: "Rhea Seehorn,Karolina Wydra,Carlos-Manuel Vesga",
    director: "Vince Gilligan",
    genre: "Drama / Sci-Fi & Fantasy",
    releaseDate: "2025-11-06",
    last_modified: "1763750784",
    rating: "8",
    rating_5based: 4,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/vNCNUxNHHgP0WsA19hxztUsG3yG.jpg",
    ],
    youtube_trailer: "lNfwe5hvEhU",
    episode_run_time: "",
    category_id: "134",
  },
  {
    num: 30,
    name: "SANDA",
    series_id: 1105259,
    tmdb_id: 258901,
    cover: "https://image.tmdb.org/t/p/w400/5Nfdb0I8Az6rwSOtS4K0HnsHEd4.jpg",
    plot: 'Jap\u00f3n, un futuro cercano. Con una natalidad muy baja, los ni\u00f1os son atesorados, pero vigilados. Santa est\u00e1 prohibido por considerarse peligroso. En Navidad, Kazushige Sanda, estudiante y descendiente de Santa, es atacado por su compa\u00f1era Fuyumura, quien quiere que encuentre a su amiga desaparecida, Ono. "Santa, encu\u00e9ntrala". Para protegerlos, Sanda se convierte en Santa y enfrenta a los adultos.',
    cast: "\u6751\u702c\u6b69,\u6771\u5730\u5b8f\u6a39,\u5e84\u53f8\u5b87\u82bd\u9999,\u6c38\u702c\u30a2\u30f3\u30ca,\u65b0\u7950\u6a39,\u677e\u5ca1\u7f8e\u91cc,Toshihiko Seki,\u5e73\u7530\u5e83\u660e,Masako Nozawa",
    director: "",
    genre: "Animaci\u00f3n / Action & Adventure / Misterio / Drama",
    releaseDate: "2025-10-04",
    last_modified: "1763750724",
    rating: "0",
    rating_5based: 0,
    backdrop_path: [
      "https://image.tmdb.org/t/p/w780/7gphZmKk3BVAeIK4AdN8GLmtoZ2.jpg",
    ],
    youtube_trailer: "",
    episode_run_time: "24",
    category_id: "126",
  },
];

const seriesCategories2 = [
  {
    category_id: "115",
    category_name: "Action & Adventure, Sci-Fi & Fantasy, Misterio",
    parent_id: 0,
  },
  {
    category_id: "114",
    category_name: "Comedia",
    parent_id: 0,
  },
  {
    category_id: "126",
    category_name: "Anime",
    parent_id: 0,
  },
  {
    category_id: "158",
    category_name: "Anime (Subtituladas)",
    parent_id: 0,
  },
  {
    category_id: "127",
    category_name: "Clasicas",
    parent_id: 0,
  },
  {
    category_id: "128",
    category_name: "Kids",
    parent_id: 0,
  },
  {
    category_id: "134",
    category_name: "Crimen, Misterio, Drama",
    parent_id: 0,
  },
  {
    category_id: "138",
    category_name: "Espana",
    parent_id: 0,
  },
  {
    category_id: "157",
    category_name: "Religioso",
    parent_id: 0,
  },
  {
    category_id: "151",
    category_name: "Doramas",
    parent_id: 0,
  },
  {
    category_id: "187",
    category_name: "Turcas",
    parent_id: 0,
  },
  {
    category_id: "143",
    category_name: "Documental",
    parent_id: 0,
  },
  {
    category_id: "142",
    category_name: "Musica",
    parent_id: 0,
  },
  {
    category_id: "139",
    category_name: "Novelas",
    parent_id: 0,
  },
  {
    category_id: "208",
    category_name: "Novelas Argentina",
    parent_id: 0,
  },
  {
    category_id: "197",
    category_name: "Novelas Brasile\u00f1as",
    parent_id: 0,
  },
  {
    category_id: "223",
    category_name: "Novelas Chilenas",
    parent_id: 0,
  },
  {
    category_id: "196",
    category_name: "Novelas Colombianas",
    parent_id: 0,
  },
  {
    category_id: "198",
    category_name: "Novelas Mexicanas",
    parent_id: 0,
  },
  {
    category_id: "207",
    category_name: "Novelas Peruanas",
    parent_id: 0,
  },
  {
    category_id: "195",
    category_name: "Novelas Telemundo",
    parent_id: 0,
  },
  {
    category_id: "194",
    category_name: "Novelas Venezolanas",
    parent_id: 0,
  },
  {
    category_id: "178",
    category_name: "National Geographic",
    parent_id: 0,
  },
  {
    category_id: "159",
    category_name: "Doramas (Subtituladas)",
    parent_id: 0,
  },
  {
    category_id: "180",
    category_name: "Ingles (Subtituladas)",
    parent_id: 0,
  },
  {
    category_id: "171",
    category_name: "Horror",
    parent_id: 0,
  },
  {
    category_id: "173",
    category_name: "Sport",
    parent_id: 0,
  },
  {
    category_id: "179",
    category_name: "Reality",
    parent_id: 0,
  },
  {
    category_id: "190",
    category_name: "Vix+ Original",
    parent_id: 0,
  },
  {
    category_id: "192",
    category_name: "Peacock Original",
    parent_id: 0,
  },
  {
    category_id: "193",
    category_name: "Prime Video Original",
    parent_id: 0,
  },
  {
    category_id: "218",
    category_name: "Fitness",
    parent_id: 0,
  },
  {
    category_id: "154",
    category_name: "18+",
    parent_id: 0,
  },
];

const live = [
  {
    num: 1,
    name: "CR: TD+ 1 [HD]",
    stream_type: "live",
    stream_id: 60875,
    stream_icon: "https://pagina.win/logos/cr/td.png",
    epg_channel_id: null,
    added: "1637258692",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 2,
    name: "[CHI] TNT SPORTS",
    stream_type: "live",
    stream_id: 65798,
    stream_icon: "https://pagina.win/logos/ch/TNTSPORTS.png",
    epg_channel_id: null,
    added: "1637595962",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 3,
    name: "[CINE] SONY (e)",
    stream_type: "live",
    stream_id: 971075,
    stream_icon: "https://pagina.win/logos/ca/sony.png",
    epg_channel_id: null,
    added: "1685245744",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 4,
    name: "[CULT] DISCOVERY H&H (e)",
    stream_type: "live",
    stream_id: 661679,
    stream_icon: "https://pagina.win/logos/ca/HomeandHealth.png",
    epg_channel_id: null,
    added: "1672884123",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 5,
    name: "[CULT] HISTORY (e)",
    stream_type: "live",
    stream_id: 987637,
    stream_icon: "https://pagina.win/logos/ca/HistoryChannel.png",
    epg_channel_id: null,
    added: "1691169223",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 6,
    name: "[CULT] NAT GEO (e)",
    stream_type: "live",
    stream_id: 987640,
    stream_icon: "https://pagina.win/logos/ca/NatGeo.png",
    epg_channel_id: null,
    added: "1691169343",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 7,
    name: "[KIDS] TEEN NICK",
    stream_type: "live",
    stream_id: 379045,
    stream_icon: "https://pagina.win/logos/ki/teennick.png",
    epg_channel_id: null,
    added: "1660427462",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 8,
    name: "[PER] ATV (e)",
    stream_type: "live",
    stream_id: 1083293,
    stream_icon: "https://pagina.win/logos/pe/atv.png",
    epg_channel_id: null,
    added: "1741448589",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 9,
    name: "[SPORT] ESPN 1 ARG",
    stream_type: "live",
    stream_id: 44488,
    stream_icon: "https://pagina.win/logos/de/espn.png",
    epg_channel_id: null,
    added: "1636345438",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 10,
    name: "[SPORT] ESPN 2 ARG",
    stream_type: "live",
    stream_id: 44487,
    stream_icon: "https://pagina.win/logos/de/espn2.png",
    epg_channel_id: null,
    added: "1636345438",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 11,
    name: "[SPORT] ESPN 3 ARG",
    stream_type: "live",
    stream_id: 44486,
    stream_icon: "https://pagina.win/logos/de/espn3.png",
    epg_channel_id: null,
    added: "1636345438",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 12,
    name: "[SPORT] ESPN 4 (ARG)",
    stream_type: "live",
    stream_id: 44485,
    stream_icon: "https://pagina.win/logos/de/espn4.png",
    epg_channel_id: null,
    added: "1636345438",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 13,
    name: "[SPORT] ESPN PREMIUM (AR)",
    stream_type: "live",
    stream_id: 182370,
    stream_icon: "https://pagina.win/logos/de/espnpremiun.png",
    epg_channel_id: null,
    added: "1640712787",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 14,
    name: "[SPORT] FOX SPORTS 2 (AR)",
    stream_type: "live",
    stream_id: 44483,
    stream_icon: "https://pagina.win/logos/de/foxsports2.png",
    epg_channel_id: null,
    added: "1636345438",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 15,
    name: "[SPORT] FOX SPORTS 3 (AR)",
    stream_type: "live",
    stream_id: 44482,
    stream_icon: "https://pagina.win/logos/de/foxsports3.png",
    epg_channel_id: null,
    added: "1636345438",
    is_adult: "0",
    category_id: "162",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 16,
    name: "Sexo en La Ciudad (SD)",
    stream_type: "live",
    stream_id: 43444,
    stream_icon: "https://pagina.win/logos/247/Top/Sc.png",
    epg_channel_id: null,
    added: "1634624215",
    is_adult: "0",
    category_id: "152",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 17,
    name: "[HD] ADULT 1 (Xc+)",
    stream_type: "live",
    stream_id: 66752,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638044506",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 18,
    name: "[HD] ADULT 2 (Xc+)",
    stream_type: "live",
    stream_id: 66753,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638044530",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 19,
    name: "[HD] ADULT 3 (Xc+)",
    stream_type: "live",
    stream_id: 66754,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638044566",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 20,
    name: "[HD] ADULT 4 (Xc+)",
    stream_type: "live",
    stream_id: 66755,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638044594",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 21,
    name: "[HD] ADULT 5 (Xc+)",
    stream_type: "live",
    stream_id: 66756,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638044620",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 22,
    name: "[HD] ADULT 6 (Xc+)",
    stream_type: "live",
    stream_id: 66757,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638044675",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 23,
    name: "[HD] ADULT 7 (Xc+)",
    stream_type: "live",
    stream_id: 66758,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638044924",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 24,
    name: "[HD] ADULT 8 (Xc+)",
    stream_type: "live",
    stream_id: 66759,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638045130",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 25,
    name: "[HD] ADULT 9 (Xc+)",
    stream_type: "live",
    stream_id: 66760,
    stream_icon: "https://pagina.win/logos/xx/adultos.png",
    epg_channel_id: null,
    added: "1638045213",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 26,
    name: "[HD] BANG VL 1 (xc+)",
    stream_type: "live",
    stream_id: 250013,
    stream_icon: "https://i.imgur.com/hKbyNBK.png",
    epg_channel_id: null,
    added: "1654528272",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 27,
    name: "[HD] FAKE HOSTEL (xc+)",
    stream_type: "live",
    stream_id: 194488,
    stream_icon: "https://i.imgur.com/XN5JX8G.png",
    epg_channel_id: null,
    added: "1644639924",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 28,
    name: "[HD] FAKE TAXI (xc+)",
    stream_type: "live",
    stream_id: 194525,
    stream_icon: "https://i.imgur.com/Rc7Awx4.png",
    epg_channel_id: null,
    added: "1644682316",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 29,
    name: "[HD] FAKINGS (xc+)",
    stream_type: "live",
    stream_id: 194464,
    stream_icon: "https://i.imgur.com/NYRo5iz.png",
    epg_channel_id: null,
    added: "1644600319",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
  {
    num: 30,
    name: "[HD] HOUSE O FYRE (xc+)",
    stream_type: "live",
    stream_id: 195349,
    stream_icon: "https://i.imgur.com/bL2poJD.png",
    epg_channel_id: null,
    added: "1645073781",
    is_adult: "0",
    category_id: "113",
    custom_sid: "",
    tv_archive: 0,
    direct_source: "",
    tv_archive_duration: 0,
  },
];

const liveCategories2 = [
  {
    category_id: "112",
    category_name: "Cinema - Series",
    parent_id: 0,
  },
  {
    category_id: "109",
    category_name: "Cultura",
    parent_id: 0,
  },
  {
    category_id: "110",
    category_name: "Kids",
    parent_id: 0,
  },
  {
    category_id: "111",
    category_name: "Sports",
    parent_id: 0,
  },
  {
    category_id: "221",
    category_name: "ESPN & FOX SPORTS",
    parent_id: 0,
  },
  {
    category_id: "222",
    category_name: "DIRECTV SPORTS",
    parent_id: 0,
  },
  {
    category_id: "156",
    category_name: "EVENTOS",
    parent_id: 0,
  },
  {
    category_id: "104",
    category_name: "Ecuador",
    parent_id: 0,
  },
  {
    category_id: "107",
    category_name: "Bolivia",
    parent_id: 0,
  },
  {
    category_id: "108",
    category_name: "Peru",
    parent_id: 0,
  },
  {
    category_id: "105",
    category_name: "Colombia",
    parent_id: 0,
  },
  {
    category_id: "144",
    category_name: "Argentina",
    parent_id: 0,
  },
  {
    category_id: "106",
    category_name: "Chile",
    parent_id: 0,
  },
  {
    category_id: "146",
    category_name: "Paraguay",
    parent_id: 0,
  },
  {
    category_id: "160",
    category_name: "Espa\u00f1a",
    parent_id: 0,
  },
  {
    category_id: "145",
    category_name: "Uruguay",
    parent_id: 0,
  },
  {
    category_id: "130",
    category_name: "Venezuela",
    parent_id: 0,
  },
  {
    category_id: "188",
    category_name: "Brasil",
    parent_id: 0,
  },
  {
    category_id: "147",
    category_name: "Telenovelas",
    parent_id: 0,
  },
  {
    category_id: "133",
    category_name: "Mexico",
    parent_id: 0,
  },
  {
    category_id: "136",
    category_name: "Nicaragua",
    parent_id: 0,
  },
  {
    category_id: "135",
    category_name: "Panama",
    parent_id: 0,
  },
  {
    category_id: "165",
    category_name: "Honduras",
    parent_id: 0,
  },
  {
    category_id: "155",
    category_name: "Republica Dominicana",
    parent_id: 0,
  },
  {
    category_id: "166",
    category_name: "El Salvador",
    parent_id: 0,
  },
  {
    category_id: "167",
    category_name: "Costa Rica",
    parent_id: 0,
  },
  {
    category_id: "181",
    category_name: "Guatemala",
    parent_id: 0,
  },
  {
    category_id: "176",
    category_name: "Puerto Rico",
    parent_id: 0,
  },
  {
    category_id: "137",
    category_name: "MUSICA",
    parent_id: 0,
  },
  {
    category_id: "206",
    category_name: "USA SPORTS",
    parent_id: 0,
  },
  {
    category_id: "230",
    category_name: "DAZN",
    parent_id: 0,
  },
  {
    category_id: "212",
    category_name: "MLS",
    parent_id: 0,
  },
  {
    category_id: "215",
    category_name: "MLB",
    parent_id: 0,
  },
  {
    category_id: "216",
    category_name: "NFL",
    parent_id: 0,
  },
  {
    category_id: "213",
    category_name: "NBA",
    parent_id: 0,
  },
  {
    category_id: "217",
    category_name: "NHL",
    parent_id: 0,
  },
  {
    category_id: "161",
    category_name: "24/7 Animados",
    parent_id: 0,
  },
  {
    category_id: "152",
    category_name: "24/7 Canales",
    parent_id: 0,
  },
  {
    category_id: "177",
    category_name: "Religion",
    parent_id: 0,
  },
  {
    category_id: "132",
    category_name: "Noticia",
    parent_id: 0,
  },
  {
    category_id: "164",
    category_name: "USA",
    parent_id: 0,
  },
  {
    category_id: "162",
    category_name: "CANALES FHD",
    parent_id: 0,
  },
  {
    category_id: "113",
    category_name: "Adultos",
    parent_id: 0,
  },
];

window.AllMoviesData = movies;
window.AllMovieCategories = moviesCategories2;
window.AllLiveData = live;
window.AllLiveCategories = liveCategories2;
window.AllSeriesData = series;
window.AllSeriesCategories = seriesCategories2;
